---
title: "SCS_Paige_Thompson_Analysis"
author: "Sumeeth Guda"
date: "2024-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Libraries
```{R}
library(ggplot2)
library(pscl)
library(lmtest)
library(MASS)
library(statmod)
```


### Reading in Dataset
```{r}
dat = read.csv("N:\\SCS\\SCS Client Files\\Active Spring 2024\\22-112 Thompson\\SCS_Analysis.csv")
dat$toy_type = paste(dat$Size,"-",dat$Weight)

dat
```
### Likelihood Ratio Test
```{r}
# function for Likelihood ratio test
lrt <- function (obj1, obj2) {
  L0 <- logLik(obj1)
  L1 <- logLik(obj2)
  L01 <- as.vector(- 2 * (L0 - L1))
  df <- attr(L1, "df") - attr(L0, "df")
  list(L01 = L01, df = df,
       "p-value" = pchisq(L01, df, lower.tail = FALSE))
}

```

```{r}
df$Age <- factor(dat$Age)
dat$toy_size <- factor(dat$Size)
dat$toy_weight <- factor(dat$Weight)
dat$toy_type <- factor(dat$toy_type)
class(dat$Age)
class(dat$toy_size)
class(dat$toy_type)
```

## Visualization 1
```{r}
# Data visualizations
e <- ggplot(dat, aes(x = toy_type, y = value))

#e + geom_boxplot()

e2 <- e + geom_boxplot(aes(fill = Age), position = position_dodge(0.9) )
e2
```


```{r}
# Poisson model
pois_mod <- glm(value ~ Age + toy_weight + toy_size, data = dat, family = poisson(link = "log"))

summary(pois_mod)
qr <- qresiduals(pois_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(pois_mod), qr)

# dispersion of the Poisson model
E2 <- resid(pois_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(pois_mod))  
sum(E2^2) / (N - p)
```

```{r}
# QuasiPoisson model
qpois_mod <- glm(value ~ Age + toy_weight + toy_size, data = dat, family = quasipoisson(link = 'log'))#poisson(link = "log"))

summary(qpois_mod)
qr <- qresiduals(qpois_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(qpois_mod), qr)

# dispersion of the quasiPoisson model
E2 <- resid(qpois_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(qpois_mod))  
sum(E2^2) / (N - p)

```

```{r}
# Negative biomial model 
#(if the dispersion of the Poisson > 1.1)
nb_mod <- glm.nb(value ~ Age + toy_weight + toy_size , data = dat)
summary(nb_mod)
qr <- qresiduals(nb_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(nb_mod), qr)

E2 <- resid(nb_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(nb_mod))  
sum(E2^2) / (N - p)
```

```{r}
# ZIP model with Poisson 
m1 <- zeroinfl(value ~  toy_weight +toy_size | toy_size, data = dat)
summary(m1)
```

```{r}
## Exponentiated coefficients of the ZIP model
expCoef <- exp(coef((m1)))
expCoef <- matrix(expCoef, ncol = 2)
colnames(expCoef) <- c("Count_model","Zero_inflation_model")
expCoef

# dispersion calculation
E2 <- resid(m1, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(m1))  
sum(E2^2) / (N - p)
```


Likelihood Ratio Tests
```{r}
# Likelihood ratio tests
print("negative binomial vs ZIP")
lrt(nb_mod, m1) # negative binomial vs ZIP
print("Poisson vs ZIP")
lrt(pois_mod, m1) # Poisson vs ZIP
print("QuasiPoisson vs ZIP")
lrt(qpois_mod, m1) # QuasiPoisson VS ZIP

print("Negateive binomial vs poisson")
lrtest(pois_mod, nb_mod) # Negateive binomial vs poisson
print("Poisson vs quasipoisson")
lrtest(pois_mod, qpois_mod) #poisson vs quasipoisson
print("Quasipoisson vs Negative Binomial")
lrtest(qpois_mod, nb_mod) #qpoisson vs negative Binomial
```

# 2 toy analysis

### Reading in Dataset
```{r}
dat = read.csv("N:\\SCS\\SCS Client Files\\Active Spring 2024\\22-112 Thompson\\SCS_Analysis_DF_2Toy.csv")
dat$toy_type = paste(dat$Size,"-",dat$Weight)

dat
```

```{r}
df$Age <- factor(dat$Age)
dat$toy_1_size <- factor(dat$Toy_1_Size)
dat$toy_2_size <- factor(dat$Toy_2_Size)

dat$toy_1_weight <- factor(dat$Toy_1_Weight)
dat$toy_2_weight <- factor(dat$Toy_2_Weight)

dat$toy_type <- factor(dat$toy_type)

class(dat$Age)
class(dat$toy_1_size)
class(dat$toy_2_size)

class(dat$toy_type)
```

## Visualization 1
```{r}
# Data visualizations
e <- ggplot(dat, aes(x = toy_type, y = value))

#e + geom_boxplot()

e2 <- e + geom_boxplot(aes(fill = Age), position = position_dodge(0.9) )
e2

```
```{r}
# Poisson model
pois_mod <- glm(value ~ Age + toy_1_size + toy_2_size  + toy_2_weight + toy_1_weight, data = dat, family = poisson(link = "log"))

summary(pois_mod)
qr <- qresiduals(pois_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(pois_mod), qr)

# dispersion of the Poisson model
E2 <- resid(pois_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(pois_mod))  
sum(E2^2) / (N - p)
```

```{r}
# QuasiPoisson model
qpois_mod <- glm(value ~ Age + toy_1_size + toy_2_size  + toy_2_weight + toy_1_weight, data = dat, family = quasipoisson(link = 'log'))#poisson(link = "log"))

summary(qpois_mod)
qr <- qresiduals(qpois_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(qpois_mod), qr)

# dispersion of the quasiPoisson model
E2 <- resid(qpois_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(qpois_mod))  
sum(E2^2) / (N - p)

```



```{r}
# Negative biomial model 
#(if the dispersion of the Poisson > 1.1)
nb_mod <- glm.nb(value ~  Age + toy_1_size + toy_2_size  + toy_2_weight + toy_1_weight, data = dat)
summary(nb_mod)
qr <- qresiduals(nb_mod)
qqnorm(qr)
abline(0,1)
plot(fitted(nb_mod), qr)

E2 <- resid(nb_mod, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(nb_mod))  
sum(E2^2) / (N - p)

```

```{r}

# ZIP model with Poisson 
m1 <- zeroinfl(value ~ toy_1_size + toy_2_size  + toy_2_weight + toy_1_weight, data = dat)
summary(m1)

```


```{r}
## Exponentiated coefficients of the ZIP model
expCoef <- exp(coef((m1)))
expCoef <- matrix(expCoef, ncol = 2)
colnames(expCoef) <- c("Count_model","Zero_inflation_model")
expCoef

# dispersion calculation
E2 <- resid(m1, type = "pearson")
N  <- nrow(dat)
p  <- length(coef(m1))  
sum(E2^2) / (N - p)
```

Likelihood Ratio Tests
```{r}
# Likelihood ratio tests
print("negative binomial vs ZIP")
lrt(nb_mod, m1) # negative binomial vs ZIP
print("Poisson vs ZIP")
lrt(pois_mod, m1) # Poisson vs ZIP
print("QuasiPoisson vs ZIP")
lrt(qpois_mod, m1) # QuasiPoisson VS ZIP

print("Negateive binomial vs poisson")
lrtest(pois_mod, nb_mod) # Negateive binomial vs poisson
print("Poisson vs quasipoisson")
lrtest(pois_mod, qpois_mod) #poisson vs quasipoisson
print("Quasipoisson vs Negative Binomial")
lrtest(qpois_mod, nb_mod) #qpoisson vs negative Binomial
```






